git:
  depth: 1

language: swift
os: osx
osx_image: xcode11.5

# https://docs.travis-ci.com/user/caching/
cache:
  bundler: true
  cocoapods: true

before_install:
  - bundle install

install:
  - bundle exec pod install

jobs:
  include:
    - name: iOS 13 Tests
      script: Scripts/run_ios13_tests.sh

    - name: iOS 12 Tests
      script: Scripts/run_ios12_tests.sh

    - name: iOS 11 Tests
      script: Scripts/run_ios11_tests.sh

    - name: iOS 10 Tests
      script: Scripts/run_ios10_tests.sh
