# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  ios_11_tests:

    macos:
      xcode: 11.7.0

    steps:
      - checkout
      #- run: bundle install
      #- run: bundle exec pod install --repo-update
      - run: xcrun simctl list
      #- run: Scripts/run_ios11_tests.sh

  ios_12_tests:

    macos:
      xcode: 12.2.0

    steps:
      - checkout
      - run: bundle install
      - run: bundle exec pod install --repo-update

workflows:
  run_all_tests:
    jobs:
      - ios_11_tests
      #- ios_12_tests

